### ISSUE TITLE
regarding "If you have some good recommendations, please tell me!"

### ISSUE THREAD

**Issue by ghost** [siddontang/tlock#5]
can you keep it simple and stupid (KISS principle) ?
I didn't run your daemon, but in docs, I see that REST request POST returns lock_id..

How about, true / false ? return lock_id if locking is successful, return "false" as string if locking is not released yet. and return "error" if something goes wrong.

I'm just sharing my recommendation :)
BTW, thanks for your Go works. LedisDB is awesome !

And I know it's wrong place to share this: saw this at: https://github.com/siddontang/ledisdb/wiki/Benchmark

```
4) LedisDB backed by HyperLevelDB performs better than by 'leveldb' and 'rocksdb'.
```

But, it looks like rocksdb performs better, for get-set,lpush,lrange according to http://ledisdb.com/ graphics.
:)

**Comment by ghost** [comment]
- how about unlocking (or also) by key instead of lock_id?

**Comment by siddontang** [comment]
Hi @faaliyet 

Why I return `lockid` instead of lock/unlock with key and true/false is that I want to avoid the scenario that other may unlock it with key wrongly. 

E.g:

```
// shell1
http lock by key like abc
// do something
http unlock with abc

// shell2
// something goes wrong
http unlock with abc
```

As you see, because we cannot know lock id, so others can not unlock it wrongly.

**Comment by siddontang** [comment]
The benchmark for LedisDB is not updated for a long time, because I am very busy in a startup :-)

Now we use rocksdb mainly in our product, this is very fast and robust, don't care heyperleveldb is better than rocksdb, I think they can all fit your need, and single machine becomes bottleneck, we may will cluster instead.

Btw, I just do a simple benchmark, so I can not tell which backend is the best.

**Comment by faaliyet** [comment]
Thanks for your response :) yeah, probably you're busy too much :) since you have great skills and efforts :)

**Comment by ghost** [comment]
```
// shell1
http lock by key like abc
// do something
http unlock with abc

// shell2
// something goes wrong
http unlock with abc
```

I still no see the reason, why you use locking in this way. 
in shell 2 ?

```
if ( lock !== false) continue();  unlock(key);
if ( lock === false) do_not_continue();
?
```

anyway, it looks like you know what you're doing :) so, yeah, i'm out of this concept. :)

**Comment by siddontang** [comment]
You may see that I wrote something goes wrong in shell2. e,g, if shell2 want to unlock 1234, but we pass abc wrongly, shell2 may unlock abc, this is the risk for lock/unlock with key.

Atm, I recommend you use RESP session lock, not restful HTTP. E.g,

```
RESP lock key
// here app crashes
RESP unlock key
```

If app crashes, using restful HTTP can not unlock, but for RESP session, tlock will check the connection is closed and unlock the locks grabbed by the session, this is very similar like zookeeper session.

**Comment by ghost** [comment]
```
 if shell2 want to unlock 1234, but we pass abc wrongly, 
```

wrongly? so, it is programmer's fault :) and that's all. I first time see this kind of approach. good or bad , I have no idea.

second,
no, no , you've understood me wrong.  I'm not talking about the protocol HTTP or RESP, the point was about returning values, lock_id/false , in the example, I see only lock_id. But I think, returning false value when lock is there, is better approach. Think as "zookeeper distr. locking" not "etcd".

https://github.com/Gutza/php-zookeeper-recipes
https://github.com/ronnylt/redlock-php

anyway, I don't want to waste your time :) better, focus on your startup project :)

**Comment by siddontang** [comment]
For http api, 200 is ok (true + lockid), and 408 (request timeout) is not ok (false). I use http status for true/false.

**Comment by ghost** [comment]
Oh, finally! that was the question from the beginning :D You might want to include 408 example. Thanks for the clarification :+1:

**Comment by siddontang** [comment]
Sorry for my poor english. I should understand what you mean earlier.

**Comment by ghost** [comment]
Don't say this, my english is poor as well :) It clearly was my fault, I had to be more clear about it :) Please keep your effort up !
